[package]
name = "si_project"
version = "0.1.0"
edition = "2021"

[dependencies]
burn = { version = "0.16", features = ['train', 'autodiff', 'wgpu', 'cuda-jit'] }
serde = "1.0"
serde-pickle = "1.2.0"
cli-table = "0.4"
rand = "0.8.5"
